blank_issues_enabled: false
issue_templates:
  - name: Bug report
    description: Create a bug report to help us improve the project
    template: bug_report.yml
  - name: Feature request
    description: Suggest a new feature for the KAGOME project
    template: feature_request.yml
